### ISSUE TITLE
Cannot read property 'directiveMatch' of undefined

### ISSUE THREAD

**Issue by Ethaan** [CulturalMe/meteor-slingshot#104]
Currently im trying to upload a file using temporary AWS Credentials .

This is how my server/config/directives.js looks.
```javascript
var AWS = Meteor.npmRequire('aws-sdk');
var sts = new AWS.STS(); 

Slingshot.createDirective('myUploads', Slingshot.S3Storage.TempCredentials, {
  bucket: 'myBucket',
  region: "US-Standard",
  AWSAccessKeyId: "xxxx",
  AWSSecretAccessKey : "xxx",
  allowedFileTypes: ["image/png", "image/jpeg", "image/gif"],
  maxSize: 10 * 1024 * 1024,
  authorize:function(){
    return true;
  },
  temporaryCredentials: Meteor.wrapAsync(function (expire, callback) {
    //AWS dictates that the minimum duration must be 900 seconds:
    var duration = Math.max(Math.round(expire / 1000), 900);

    sts.getSessionToken({
        DurationSeconds: duration
    }, function (error, result) {
      callback(error, result && result.Credentials);
    });
  })
});
```

But i get this error.

```TypeError: Cannot read property 'directiveMatch' of undefined```

This is the only configuration i have, im missing something?

BTW Great Packge

**Comment by Ethaan** [comment]
Just saw that you stage a new version (0.7.1), changing my package to ```'edgee:slingshot@0.7.0'```, solve the problem

**Comment by gsuess** [comment]
`Slingshot.S3Storage.TempCredentials` is a very new feature that came out in 0.7.0 and it is very rare to have a use-case for it, because even when you don't use temporary credentials, the signature hashes used in the upload are secure, will expire (in 300 seconds by default) and cannot be reused for any other purposes than uploading one single file.

So I wonder, out of curiosity, what is your use-case for creating the signature with temporary credentials?

**Comment by Ethaan** [comment]
Hi @gsuess sorry for the long delay i think i have already answer the question, my bad.

Actually that was just for testing purposes, i see the option in the DOCS and want to give it a try.

**Comment by gsuess** [comment]
I see, thanks
