### ISSUE TITLE
S3 Upload successful, but cant open image

### ISSUE THREAD

**Issue by opensorceror** [CulturalMe/meteor-slingshot#165]
Hello,

I'm using the mdg:camera to get a base64 encoded image from the user's gallery.
To upload the image to Amazon S3 using Slingshot (which requires either a blob or a File, I'm using the following code to convert the base64 string to a File:

  this.dataUriToFile = (dataUri, fileName) => {
    // https://en.wikipedia.org/wiki/Data_URI_scheme
    // create a pattern to match the data uri
    var patt = /^data:([^\/]+\/[^;]+)?(;charset=([^;]+))?(;base64)?,/i,
    matches = dataUri.match(patt);
    if (matches == null){
    throw new Error("data: uri did not match scheme")
    }
    var prefix = matches[0],
    contentType = matches[1],
    // var charset = matches[3]; -- not used.
    isBase64 = matches[4] != null,
    // remove the prefix
    encodedBytes = dataUri.slice(prefix.length),
    // decode the bytes
    decodedBytes = isBase64 ? atob(encodedBytes) : encodedBytes,
    // return the file object
    props = {};
    if (contentType) {
    props.type = contentType;
    }
    return new File([decodedBytes], fileName, props);
  }

I'm able to successfully upload the file to S3. Here's an example of an uploaded image:
https://s3-us-west-2.amazonaws.com/lxc-photos/lolik/my.jpg

However, I'm not able to open the image on the S3 Console.
I'm getting an error: "The image cannot be displayed because it contains errors."

What could possibly be going wrong?

Thanks!

**Comment by y01s** [comment]
I have the same problem, Have you found a solution?
PS: in my case I'm using cordova-image-picker (https://www.npmjs.com/package/cordova-plugin-image-picker)
and then I use window.resolveLocalFileSystemURL() to get a file type.
I do a preview on the image chosen, and it's fine, but when I upload it to Amazon S3, its size is 15 byte and gave me the same error.

**Comment by y01s** [comment]
This has worked for me
http://stackoverflow.com/a/34572678/4937709

**Comment by cluxter** [comment]
I am having the exact same issue over here.

From what I understand, Slingshot doesn't handle very well the File object returned by the FireEntry.file() method (which is used to convert a FileEntry as a File object, because Cordova returns a FileEntry object). We can use a Blob object instead since Slingshot accepts both formats apparently:

https://github.com/CulturalMe/meteor-slingshot/blob/59a8b2eb637b25a904bd9ee28e3611892d5fccae/lib/upload.js#L89

But this requires manual conversion from FileEntry to Blob.

I don't understand how we end up with a 15 bytes file on the server though. If you open the uploaded file with a text editor you will see this:

`[object Object]`

= 15 bytes.

So it seems that Slingshot uploads the result of something instead of handling it right.

It would be cool to find how to patch Slingshot instead of using a hack.

**Comment by cluxter** [comment]
See this link: https://github.com/CulturalMe/meteor-slingshot/issues/49
