### ISSUE TITLE
Regarding multi file upload

### ISSUE THREAD

**Issue by simsim0709** [CulturalMe/meteor-slingshot#194]
Hello, 

Is there the best practice to deal with multi file upload? 

When a user uploads multi file uploads, I want to prevent uploading more than 10 files in the server side, not client side.

I know there is `authorize` method to deal with. However, I don't fully understand how to limit file count..

Thank you.

**Comment by gsuess** [comment]
I would suggest that you track uploads on mongo. So you could for example have a collection for FileUploads, and only allow users to insert 10 documents in FileUploads. The user will then insert a "pending upload" into file uploads and `authorize` would take the _id of the file upload and check if it exists. Once the client completes the upload, the FileUploads document will be updated according so that it is no longer pending.
