### ISSUE TITLE
Use Slingshot with DropzoneJS?

### ISSUE THREAD

**Issue by risul** [CulturalMe/meteor-slingshot#31]
I've been trying to use dropzone with slingshot for couple of days now.. dropzone requires url to post to directly... do you have any idea how I can accomplish this?

Thanks

**Comment by ChenRoth** [comment]
I just link dropzone to slingshot on initialization, using dropzone's addedfile event and slingshot's uploader.send:

```
$el.dropzone({
	init: function() {
			this.on("addedfile", function(file) {

				var uploader = mySlingshotUploader; // retrieved from somewhere else
				uploader.send(file, function (error, downloadUrl) {
					// your code here
                                });
                      })
    });
```

**Comment by komrad** [comment]
Thanks for this!

How do I get the downloadUrl using this implementation?

**Comment by komrad** [comment]
Thanks for this.

I wonder if it's possible to change the key at the point of sending? I want to manually trigger the Dropzone queue processing (i.e. dz.processQueue()) at one point (together with submitting an autoform) and then use the returned form id as the file's folder in S3.

I tried to attempt something hacky like this:
```
this.on("sending", function(file, xhr, formData) {
        file.postData[0].value = "formid/" + file.name;
        _.each(file.postData, function(field){
                formData.append(field.name, field.value);
        })
      }),
```
But it won't upload because it's different from the key returned by the Server Directive (or so I guess).

Any tips on how I could  accomplish this?
