### ISSUE TITLE
Youtube Uploader

### ISSUE THREAD

**Issue by MichaelFBA** [CulturalMe/meteor-slingshot#88]
Do you think slingshot could be used to upload video data to youtube via their api?

**Comment by gsuess** [comment]
Good question. Does youtube support signed uploads?

**Comment by gsuess** [comment]
It doesn't look like youtube would support this. As of Version 3.0 of the youtube API you need to provice an OAuth2 token with your uploads.

So that gives you four options:

 1. Expose your oauth tokens to the client, potentially granting the client more access to your youtube account than intended. I really don't recommend this.
 2. Proxy the upload through the meteor server. (Adds a lot of load to the server)
 3. Proxy the upload through a specialized server.
 4. Let users upload videos into their own accounts (you will need send them to an oauth authorization prompt, before the upload can start). 

Now slingshot is not suitable for 1. and 2. and 4. although it would be possible to use slingshot for it. It's just not the right tool for it.

However for 3. you can add signed upload support to your server.

**Comment by npaton** [comment]
Just came to mind, I have not tried this but one solution might be to use AWS Lambda along with S3. 

An upload on S3 can be a trigger for Lambda, then run a simple upload to YouTube script in Lambda et voilà. No publicly sharing your key, very little code and no meteor backend overhead. Not sure about how you add metadata to YT upload (description, title...) Maybe custom http headers if that is possible with Slingshot? You can find out more in AWS' documentation.

**Comment by gsuess** [comment]
I like the the idea @npaton. That should work and be relatively easy to setup.

**Comment by MichaelFBA** [comment]
Thanks for all the suggestions. 

I have a setup that use's Meteor server to retrieve new access tokens, so I am able to avoid exposing anything on the client. The suggestion from @npaton sounds like it would work, but there is also the returned information (url, screenshots etc) from youtube that I would need to reintegrate into the meteor world.

Cheers for your help.

**Comment by gsuess** [comment]
@MichaelFBA the access tokens that you refer to are not for a single uploads, but all uploads, right? If not can you please point me to the docs that cover the access tokesn that refer to?

**Comment by MichaelFBA** [comment]
Yeah, its just a standard oauth credential.

You can create your own oauth ID and client secret in the google dev console.
Then use this: https://developers.google.com/oauthplayground/`

Then I use the refresh token on the server to make a new request for an access_token (which i send back to the client) to allow uploading to a single youtube account without requiring someone to login.

Like you I want to avoid uploading to the meteor server than again to another service.

**Comment by gsuess** [comment]
So if the client obtains  that key he will be able to uplaod as many videos as he wants by any name as long as the key is not explicitly invalidated.

**Comment by MichaelFBA** [comment]
Hmm, now that you say it that way it could be insecure :)

**Comment by gsuess** [comment]
The idea of slingshot is that anything you define in the directive wil be enforced such that the client cannot bypass the directive.

You can implement youtube into slingshot as per point 1 as I've mentioned above.

Youtube's API is very limited in that you can only authorize certain users and set an expiry. Video names, length of the video etc. etc. cannot be enforce and therefore should not really be part of the directive, but of the request meta.

I've got some working code for OAuth in [this branch](https://github.com/CulturalMe/meteor-slingshot/tree/google-cloud-resumable) that you could use.

**Comment by MichaelFBA** [comment]
Cool, thanks.

I'll have a look-see.
